/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef anti_spam_CONSTANTS_H
#define anti_spam_CONSTANTS_H

#include "anti_spam_types.h"

namespace cls {

class anti_spamConstants {
 public:
  anti_spamConstants();

};

extern const anti_spamConstants g_anti_spam_constants;

} // namespace

#endif
